#default
#server.port: 8443
#server.ssl.enabled: true
#server.ssl.key-store: classpath:store.jks
#server.ssl.key-password: secret
#management.port: 8080
#management.ssl.enabled: false
debug: true

#resources
spring.resources.chain.enabled: true
spring.resources.chain.cache: true
spring.resources.chain.gzipped: true
spring.resources.static-locations: file:E:\WorkSpace\webpack\public\ # 坑壁window一定要以\结尾
server.display-name: nbsaw

#session
#server.session.cookie.questionComment= # Comment for the session cookie.
#server.session.cookie.pojo= # Domain for the session cookie.
server.session.cookie.http-only: true # "HttpOnly" flag for the session cookie.
server.session.cookie.max-age: 604800 # Maximum age of the session cookie in seconds.
server.session.timeout: 604800
server.session.cookie.name: miaohu # Session cookie name.
server.session.cookie.path: / # Path of the session cookie.

#terminal color setting
spring.output.ansi.enabled: always
#banner
#banner.image.width: 60 # Width of the banner image in chars (default 76)
#banner.image.height: 20 # Height of the banner image in chars (default based on image height)
#banner.image.margin: 0
#banner.charset: UTF-8
#banner.image.location: classpath:temp.png
#spring.main.banner-mode: off

#environment
#spring.profiles.active: development

#HTTP encoding
spring.http.encoding.charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring.http.encoding.enabled: true # Enable http encoding support.


# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

spring.datasource.url: jdbc:mysql://localhost:3306/project?characterEncoding=UTF-8&useSSL=true
spring.datasource.username: root
spring.datasource.password: 25802580
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring.jpa.show-sql: true
spring.jpa.database: MYSQL
spring.data.jpa.repositories.enabled: true

# log info setting
#server.tomcat.accesslog.directory: /home/fz/TempTest
#server.tomcat.accesslog.pattern: common
#server.tomcat.accesslog.request-attributes-enabled: false
#server.tomcat.accesslog.enabled: true
#server.tomcat.accesslog.suffix: .log

#spring-boot
#logging.file: my.log
#logging.level.org.springframework: ERROR

# REDIS (RedisProperties)
spring.redis.database: 2 # Database index used by the connection factory.
spring.redis.host: localhost # Redis server host.
spring.redis.password:
spring.redis.ssl: false # Enable SSL support.
spring.redis.pool.max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
spring.redis.pool.max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
spring.redis.pool.max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
spring.redis.pool.min-idle: 0 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
spring.redis.port: 6379 # Redis server port.s
spring.redis.timeout: 2000 # Connection timeout in milliseconds.