# 默认配置
project:
      name : miaohu
      version : 0.1.0
 
# 默认的服务器配置
server:
      ssl:
          key-store: keystore.p12
          key-store-password: 25802580
          keyStoreType: PKCS12
          keyAlias: tomcat

# 环境设置
spring.profiles.active: dev

# jwt设置
jwt.timeout: 604800000
jwt.key: miaohu233333

# 终端颜色设置
spring.output.ansi.enabled: always

# http的编码设置
spring.http.encoding.charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring.http.encoding.enabled: true # Enable http encoding support.

# 404 错误处理,不设置的话默认是404 page,对restful server不太友好
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false


# 数据库设置
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/project
spring.datasource.connectionPropertie: useUnicode=true;characterEncoding=utf-8;
spring.datasource.username: root
spring.datasource.password: 25802580
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring.jpa.show-sql: true
spring.jpa.database: MYSQL
spring.data.jpa.repositories.enabled: true

# REDIS的相关配置
spring.redis.database: 2 # Database index used by the connection factory.
spring.redis.host: 127.0.0.1 # Redis server host.
spring.redis.password:
spring.redis.ssl: false # Enable SSL support.
spring.redis.pool.max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
spring.redis.pool.max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
spring.redis.pool.max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
spring.redis.pool.min-idle: 0 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
spring.redis.port: 6379 # Redis server port.s
spring.redis.timeout: 2000 # Connection timeout in milliseconds.

# Redis 常量
# 图片验证码
redis.constant.image: ":IMAGE" # 图片验证码在redis的后缀
redis.constant.imageTimeOut: 5 # 图片验证码超时时间

# 手机验证码
redis.constant.phone: ":phone" # 手机验证码在redis的后缀
redis.constant.phoneTimeOut: 3 # 手机验证码超时时间


---
# 开发环境
spring.profiles: dev
server:
      port: 8443
      address: 0.0.0.0

# 资源设置
#spring.resources.chain.enabled: true
#spring.resources.chain.cache: true
#spring.resources.chain.gzipped: true
#spring.resources.static-locations: file:E:\javascript\webpack\public\ # 坑壁window一定要以\结尾

# debug信息开启
debug: true
---
# 生产环境
server:
      port: 443
      address: 0.0.0.0
spring.profiles: pro
